name: EthicalCheck-Workflow

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  schedule:
    - cron: '26 22 * * 6'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_EthicalCheck:
    permissions:
      security-events: write     # needed for upload-sarif
      actions: read              # needed in private repos for run status
    runs-on: ubuntu-latest

    steps:
      - name: EthicalCheck – Free & Automated API Security Testing Service
        uses: apisec-inc/ethicalcheck-action@005fac321dd843682b1af6b72f30caaf9952c641
        with:
          # OpenAPI spec URL / Swagger path / public Postman collection URL
          oas-url: "http://netbanking.apisec.ai:8080/v2/api-docs"
          # Email address that will receive the penetration test report
          email: "xxx@apisec.ai"
          # Output SARIF file for GitHub code scanning
          sarif-result-file: "ethicalcheck-results.sarif"

      - name: Upload SARIF file to repository
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./ethicalcheck-results.sarif
